package model;
// Generated Oct 25, 2023 3:16:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AttributeVariant generated by hbm2java
 */
@Entity
@Table(name="attribute_variant"
    ,catalog="j2e_ecom_db"
)
public class AttributeVariant  implements java.io.Serializable {


     private Integer id;
     private ProduvtAttribute produvtAttribute;
     private String variantName;
     private Double price;
     private Double discountPrice;
     private Integer qty;

    public AttributeVariant() {
    }

	
    public AttributeVariant(ProduvtAttribute produvtAttribute) {
        this.produvtAttribute = produvtAttribute;
    }
    public AttributeVariant(ProduvtAttribute produvtAttribute, String variantName, Double price, Double discountPrice, Integer qty) {
       this.produvtAttribute = produvtAttribute;
       this.variantName = variantName;
       this.price = price;
       this.discountPrice = discountPrice;
       this.qty = qty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produvt_attribute_id", nullable=false)
    public ProduvtAttribute getProduvtAttribute() {
        return this.produvtAttribute;
    }
    
    public void setProduvtAttribute(ProduvtAttribute produvtAttribute) {
        this.produvtAttribute = produvtAttribute;
    }

    
    @Column(name="variant_name", length=50)
    public String getVariantName() {
        return this.variantName;
    }
    
    public void setVariantName(String variantName) {
        this.variantName = variantName;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    
    @Column(name="discount_price", precision=22, scale=0)
    public Double getDiscountPrice() {
        return this.discountPrice;
    }
    
    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


