package model;
// Generated Nov 15, 2023 10:22:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AttributeVariant generated by hbm2java
 */
@Entity
@Table(name="attribute_variant"
    ,catalog="j2e_ecom_db"
)
public class AttributeVariant  implements java.io.Serializable {


     private Integer id;
     private Gallery gallery;
     private ProductAttribute productAttribute;
     private String variantName;
     private Double price;
     private Double discountPrice;
     private Integer qty;
     private Set<Reviews> reviewses = new HashSet<Reviews>(0);
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public AttributeVariant() {
    }

	
    public AttributeVariant(Gallery gallery, ProductAttribute productAttribute) {
        this.gallery = gallery;
        this.productAttribute = productAttribute;
    }
    public AttributeVariant(Gallery gallery, ProductAttribute productAttribute, String variantName, Double price, Double discountPrice, Integer qty, Set<Reviews> reviewses, Set<CartItem> cartItems, Set<Order> orders) {
       this.gallery = gallery;
       this.productAttribute = productAttribute;
       this.variantName = variantName;
       this.price = price;
       this.discountPrice = discountPrice;
       this.qty = qty;
       this.reviewses = reviewses;
       this.cartItems = cartItems;
       this.orders = orders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gallery_id", nullable=false)
    public Gallery getGallery() {
        return this.gallery;
    }
    
    public void setGallery(Gallery gallery) {
        this.gallery = gallery;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produvt_attribute_id", nullable=false)
    public ProductAttribute getProductAttribute() {
        return this.productAttribute;
    }
    
    public void setProductAttribute(ProductAttribute productAttribute) {
        this.productAttribute = productAttribute;
    }

    
    @Column(name="variant_name", length=50)
    public String getVariantName() {
        return this.variantName;
    }
    
    public void setVariantName(String variantName) {
        this.variantName = variantName;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    
    @Column(name="discount_price", precision=22, scale=0)
    public Double getDiscountPrice() {
        return this.discountPrice;
    }
    
    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="attributeVariant")
    public Set<Reviews> getReviewses() {
        return this.reviewses;
    }
    
    public void setReviewses(Set<Reviews> reviewses) {
        this.reviewses = reviewses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="attributeVariant")
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="attributeVariant")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


