package model;
// Generated Oct 25, 2023 3:16:17 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartItem generated by hbm2java
 */
@Entity
@Table(name="cart_item"
    ,catalog="j2e_ecom_db"
)
public class CartItem  implements java.io.Serializable {


     private Integer id;
     private Cart cart;
     private Product product;
     private String qty;

    public CartItem() {
    }

	
    public CartItem(Cart cart, Product product) {
        this.cart = cart;
        this.product = product;
    }
    public CartItem(Cart cart, Product product, String qty) {
       this.cart = cart;
       this.product = product;
       this.qty = qty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cart_id", nullable=false)
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="qty", length=45)
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }




}


