package model;
// Generated Oct 25, 2023 3:16:17 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="cart"
    ,catalog="j2e_ecom_db"
)
public class Cart  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Set<CartItem> cartItems = new HashSet<CartItem>(0);

    public Cart() {
    }

	
    public Cart(Customer customer) {
        this.customer = customer;
    }
    public Cart(Customer customer, Set<CartItem> cartItems) {
       this.customer = customer;
       this.cartItems = cartItems;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cart")
    public Set<CartItem> getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set<CartItem> cartItems) {
        this.cartItems = cartItems;
    }




}


