package model;
// Generated Dec 1, 2023 12:00:23 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CusLogin generated by hbm2java
 */
@Entity
@Table(name="cus_login"
    ,catalog="j2e_ecom_db"
)
public class CusLogin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private Date verifiedAt;
     private String verifyCode;
     private Boolean status;
     private Set<Customer> customers = new HashSet<Customer>(0);

    public CusLogin() {
    }

    public CusLogin(String username, String password, Date verifiedAt, String verifyCode, Boolean status, Set<Customer> customers) {
       this.username = username;
       this.password = password;
       this.verifiedAt = verifiedAt;
       this.verifyCode = verifyCode;
       this.status = status;
       this.customers = customers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", length=250)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="verified_at", length=19)
    public Date getVerifiedAt() {
        return this.verifiedAt;
    }
    
    public void setVerifiedAt(Date verifiedAt) {
        this.verifiedAt = verifiedAt;
    }

    
    @Column(name="verify_code", length=50)
    public String getVerifyCode() {
        return this.verifyCode;
    }
    
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cusLogin")
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


