package model;
// Generated Dec 15, 2023 11:19:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gallery generated by hbm2java
 */
@Entity
@Table(name="gallery"
    ,catalog="j2e_ecom_db"
)
public class Gallery  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private String imgPath;
     private Boolean thumbnail;
     private Date createdAt;
     private Date updatedAt;
     private Set<AttributeVariant> attributeVariants = new HashSet<AttributeVariant>(0);

    public Gallery() {
    }

	
    public Gallery(Product product) {
        this.product = product;
    }
    public Gallery(Product product, String imgPath, Boolean thumbnail, Date createdAt, Date updatedAt, Set<AttributeVariant> attributeVariants) {
       this.product = product;
       this.imgPath = imgPath;
       this.thumbnail = thumbnail;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.attributeVariants = attributeVariants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="img_path")
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    
    @Column(name="thumbnail")
    public Boolean getThumbnail() {
        return this.thumbnail;
    }
    
    public void setThumbnail(Boolean thumbnail) {
        this.thumbnail = thumbnail;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gallery")
    public Set<AttributeVariant> getAttributeVariants() {
        return this.attributeVariants;
    }
    
    public void setAttributeVariants(Set<AttributeVariant> attributeVariants) {
        this.attributeVariants = attributeVariants;
    }




}


