package model;
// Generated Dec 15, 2023 11:19:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name="order_status"
    ,catalog="j2e_ecom_db"
)
public class OrderStatus  implements java.io.Serializable {


     private int id;
     private SystemUser systemUser;
     private String status;
     private int orderId;
     private Date createdAt;
     private Set<OrderHasOrderStatus> orderHasOrderStatuses = new HashSet<OrderHasOrderStatus>(0);

    public OrderStatus() {
    }

	
    public OrderStatus(int id, int orderId) {
        this.id = id;
        this.orderId = orderId;
    }
    public OrderStatus(int id, SystemUser systemUser, String status, int orderId, Date createdAt, Set<OrderHasOrderStatus> orderHasOrderStatuses) {
       this.id = id;
       this.systemUser = systemUser;
       this.status = status;
       this.orderId = orderId;
       this.createdAt = createdAt;
       this.orderHasOrderStatuses = orderHasOrderStatuses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by")
    public SystemUser getSystemUser() {
        return this.systemUser;
    }
    
    public void setSystemUser(SystemUser systemUser) {
        this.systemUser = systemUser;
    }

    
    @Column(name="status", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="order_id", nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_at", length=10)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orderStatus")
    public Set<OrderHasOrderStatus> getOrderHasOrderStatuses() {
        return this.orderHasOrderStatuses;
    }
    
    public void setOrderHasOrderStatuses(Set<OrderHasOrderStatus> orderHasOrderStatuses) {
        this.orderHasOrderStatuses = orderHasOrderStatuses;
    }




}


