package model;
// Generated Dec 15, 2023 11:19:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderHasOrderStatus generated by hbm2java
 */
@Entity
@Table(name="order_has_order_status"
    ,catalog="j2e_ecom_db"
)
public class OrderHasOrderStatus  implements java.io.Serializable {


     private OrderHasOrderStatusId id;
     private Order order;
     private OrderStatus orderStatus;
     private SystemUser systemUser;
     private Date date;

    public OrderHasOrderStatus() {
    }

	
    public OrderHasOrderStatus(OrderHasOrderStatusId id, Order order, OrderStatus orderStatus) {
        this.id = id;
        this.order = order;
        this.orderStatus = orderStatus;
    }
    public OrderHasOrderStatus(OrderHasOrderStatusId id, Order order, OrderStatus orderStatus, SystemUser systemUser, Date date) {
       this.id = id;
       this.order = order;
       this.orderStatus = orderStatus;
       this.systemUser = systemUser;
       this.date = date;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="order_id", nullable=false, length=150) ), 
        @AttributeOverride(name="orderStatusId", column=@Column(name="order_status_id", nullable=false) ) } )
    public OrderHasOrderStatusId getId() {
        return this.id;
    }
    
    public void setId(OrderHasOrderStatusId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false, insertable=false, updatable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_status_id", nullable=false, insertable=false, updatable=false)
    public OrderStatus getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(OrderStatus orderStatus) {
        this.orderStatus = orderStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="updated_by")
    public SystemUser getSystemUser() {
        return this.systemUser;
    }
    
    public void setSystemUser(SystemUser systemUser) {
        this.systemUser = systemUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


