package model;
// Generated Dec 15, 2023 11:19:00 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="j2e_ecom_db"
)
public class Order  implements java.io.Serializable {


     private String orderId;
     private Customer customer;
     private PaymentStatus paymentStatus;
     private Date orderDate;
     private Date updateDate;
     private Double estimatedDeliveryDate;
     private Double total;
     private Double discount;
     private String trackingNumber;
     private int id;
     private Integer attributeVariantId;
     private int productId;
     private String qty;
     private Date orderDeliveredCarrierDate;
     private Date orderDeliveredCustomerDate;
     private String createdAt;
     private Set<OrderHasOrderStatus> orderHasOrderStatuses = new HashSet<OrderHasOrderStatus>(0);

    public Order() {
    }

	
    public Order(String orderId, Customer customer, PaymentStatus paymentStatus, int id, int productId) {
        this.orderId = orderId;
        this.customer = customer;
        this.paymentStatus = paymentStatus;
        this.id = id;
        this.productId = productId;
    }
    public Order(String orderId, Customer customer, PaymentStatus paymentStatus, Date orderDate, Date updateDate, Double estimatedDeliveryDate, Double total, Double discount, String trackingNumber, int id, Integer attributeVariantId, int productId, String qty, Date orderDeliveredCarrierDate, Date orderDeliveredCustomerDate, String createdAt, Set<OrderHasOrderStatus> orderHasOrderStatuses) {
       this.orderId = orderId;
       this.customer = customer;
       this.paymentStatus = paymentStatus;
       this.orderDate = orderDate;
       this.updateDate = updateDate;
       this.estimatedDeliveryDate = estimatedDeliveryDate;
       this.total = total;
       this.discount = discount;
       this.trackingNumber = trackingNumber;
       this.id = id;
       this.attributeVariantId = attributeVariantId;
       this.productId = productId;
       this.qty = qty;
       this.orderDeliveredCarrierDate = orderDeliveredCarrierDate;
       this.orderDeliveredCustomerDate = orderDeliveredCustomerDate;
       this.createdAt = createdAt;
       this.orderHasOrderStatuses = orderHasOrderStatuses;
    }
   
     @Id 

    
    @Column(name="order_id", unique=true, nullable=false, length=150)
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_status_id", nullable=false)
    public PaymentStatus getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    
    @Column(name="estimated_delivery_date", precision=22, scale=0)
    public Double getEstimatedDeliveryDate() {
        return this.estimatedDeliveryDate;
    }
    
    public void setEstimatedDeliveryDate(Double estimatedDeliveryDate) {
        this.estimatedDeliveryDate = estimatedDeliveryDate;
    }

    
    @Column(name="total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }

    
    @Column(name="discount", precision=22, scale=0)
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    
    @Column(name="tracking_number", length=100)
    public String getTrackingNumber() {
        return this.trackingNumber;
    }
    
    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="attribute_variant_id")
    public Integer getAttributeVariantId() {
        return this.attributeVariantId;
    }
    
    public void setAttributeVariantId(Integer attributeVariantId) {
        this.attributeVariantId = attributeVariantId;
    }

    
    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

    
    @Column(name="qty", length=45)
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_delivered_carrier_date", length=19)
    public Date getOrderDeliveredCarrierDate() {
        return this.orderDeliveredCarrierDate;
    }
    
    public void setOrderDeliveredCarrierDate(Date orderDeliveredCarrierDate) {
        this.orderDeliveredCarrierDate = orderDeliveredCarrierDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_delivered_customer_date", length=19)
    public Date getOrderDeliveredCustomerDate() {
        return this.orderDeliveredCustomerDate;
    }
    
    public void setOrderDeliveredCustomerDate(Date orderDeliveredCustomerDate) {
        this.orderDeliveredCustomerDate = orderDeliveredCustomerDate;
    }

    
    @Column(name="created_at", length=45)
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderHasOrderStatus> getOrderHasOrderStatuses() {
        return this.orderHasOrderStatuses;
    }
    
    public void setOrderHasOrderStatuses(Set<OrderHasOrderStatus> orderHasOrderStatuses) {
        this.orderHasOrderStatuses = orderHasOrderStatuses;
    }




}


