package model;
// Generated Dec 15, 2023 11:19:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentStatus generated by hbm2java
 */
@Entity
@Table(name="payment_status"
    ,catalog="j2e_ecom_db"
)
public class PaymentStatus  implements java.io.Serializable {


     private int id;
     private String statusCode;
     private String status;
     private Set<Order> orders = new HashSet<Order>(0);

    public PaymentStatus() {
    }

	
    public PaymentStatus(int id) {
        this.id = id;
    }
    public PaymentStatus(int id, String statusCode, String status, Set<Order> orders) {
       this.id = id;
       this.statusCode = statusCode;
       this.status = status;
       this.orders = orders;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="status_code", length=15)
    public String getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    
    @Column(name="status", length=150)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paymentStatus")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


