package model;
// Generated Nov 15, 2023 12:07:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AttributeVariant generated by hbm2java
 */
@Entity
@Table(name="attribute_variant"
    ,catalog="j2e_ecom_db"
)
public class AttributeVariant  implements java.io.Serializable {


     private Integer id;
     private String variantName;
     private Double price;
     private Double discountPrice;
     private Integer qty;
     private int produvtAttributeId;
     private int galleryId;
     private Set<Reviews> reviewses = new HashSet<Reviews>(0);

    public AttributeVariant() {
    }

	
    public AttributeVariant(int produvtAttributeId, int galleryId) {
        this.produvtAttributeId = produvtAttributeId;
        this.galleryId = galleryId;
    }
    public AttributeVariant(String variantName, Double price, Double discountPrice, Integer qty, int produvtAttributeId, int galleryId, Set<Reviews> reviewses) {
       this.variantName = variantName;
       this.price = price;
       this.discountPrice = discountPrice;
       this.qty = qty;
       this.produvtAttributeId = produvtAttributeId;
       this.galleryId = galleryId;
       this.reviewses = reviewses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="variant_name", length=50)
    public String getVariantName() {
        return this.variantName;
    }
    
    public void setVariantName(String variantName) {
        this.variantName = variantName;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    
    @Column(name="discount_price", precision=22, scale=0)
    public Double getDiscountPrice() {
        return this.discountPrice;
    }
    
    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    
    @Column(name="produvt_attribute_id", nullable=false)
    public int getProduvtAttributeId() {
        return this.produvtAttributeId;
    }
    
    public void setProduvtAttributeId(int produvtAttributeId) {
        this.produvtAttributeId = produvtAttributeId;
    }

    
    @Column(name="gallery_id", nullable=false)
    public int getGalleryId() {
        return this.galleryId;
    }
    
    public void setGalleryId(int galleryId) {
        this.galleryId = galleryId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="attributeVariant")
    public Set<Reviews> getReviewses() {
        return this.reviewses;
    }
    
    public void setReviewses(Set<Reviews> reviewses) {
        this.reviewses = reviewses;
    }




}


