package model;
// Generated Nov 15, 2023 12:07:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartItem generated by hbm2java
 */
@Entity
@Table(name="cart_item"
    ,catalog="j2e_ecom_db"
)
public class CartItem  implements java.io.Serializable {


     private Integer id;
     private Cart cart;
     private String qty;
     private int attributeVariantId;
     private Double unitprice;
     private Double total;

    public CartItem() {
    }

	
    public CartItem(Cart cart, int attributeVariantId) {
        this.cart = cart;
        this.attributeVariantId = attributeVariantId;
    }
    public CartItem(Cart cart, String qty, int attributeVariantId, Double unitprice, Double total) {
       this.cart = cart;
       this.qty = qty;
       this.attributeVariantId = attributeVariantId;
       this.unitprice = unitprice;
       this.total = total;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cart_id", nullable=false)
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

    
    @Column(name="qty", length=45)
    public String getQty() {
        return this.qty;
    }
    
    public void setQty(String qty) {
        this.qty = qty;
    }

    
    @Column(name="attribute_variant_id", nullable=false)
    public int getAttributeVariantId() {
        return this.attributeVariantId;
    }
    
    public void setAttributeVariantId(int attributeVariantId) {
        this.attributeVariantId = attributeVariantId;
    }

    
    @Column(name="unitprice", precision=22, scale=0)
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }

    
    @Column(name="total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


