package model;
// Generated Nov 15, 2023 12:07:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Gallery generated by hbm2java
 */
@Entity
@Table(name="gallery"
    ,catalog="j2e_ecom_db"
)
public class Gallery  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private String imgPath;
     private Boolean thumbnail;
     private String createdAt;
     private String updatedAt;

    public Gallery() {
    }

	
    public Gallery(Product product) {
        this.product = product;
    }
    public Gallery(Product product, String imgPath, Boolean thumbnail, String createdAt, String updatedAt) {
       this.product = product;
       this.imgPath = imgPath;
       this.thumbnail = thumbnail;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="img_path", length=445)
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    
    @Column(name="thumbnail")
    public Boolean getThumbnail() {
        return this.thumbnail;
    }
    
    public void setThumbnail(Boolean thumbnail) {
        this.thumbnail = thumbnail;
    }

    
    @Column(name="created_at", length=45)
    public String getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    
    @Column(name="updated_at", length=45)
    public String getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }




}


