package model;
// Generated Nov 15, 2023 12:07:55 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NewTable generated by hbm2java
 */
@Entity
@Table(name="new_table"
    ,catalog="j2e_ecom_db"
)
public class NewTable  implements java.io.Serializable {


     private int idnewTable;

    public NewTable() {
    }

    public NewTable(int idnewTable) {
       this.idnewTable = idnewTable;
    }
   
     @Id 

    
    @Column(name="idnew_table", unique=true, nullable=false)
    public int getIdnewTable() {
        return this.idnewTable;
    }
    
    public void setIdnewTable(int idnewTable) {
        this.idnewTable = idnewTable;
    }




}


