package model;
// Generated Nov 15, 2023 10:22:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductAttribute generated by hbm2java
 */
@Entity
@Table(name="product_attribute"
    ,catalog="j2e_ecom_db"
)
public class ProductAttribute  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private String attributeName;
     private String attributeType;
     private Set<AttributeVariant> attributeVariants = new HashSet<AttributeVariant>(0);

    public ProductAttribute() {
    }

	
    public ProductAttribute(Product product) {
        this.product = product;
    }
    public ProductAttribute(Product product, String attributeName, String attributeType, Set<AttributeVariant> attributeVariants) {
       this.product = product;
       this.attributeName = attributeName;
       this.attributeType = attributeType;
       this.attributeVariants = attributeVariants;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="attribute_name", length=50)
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    
    @Column(name="attribute_type", length=50)
    public String getAttributeType() {
        return this.attributeType;
    }
    
    public void setAttributeType(String attributeType) {
        this.attributeType = attributeType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productAttribute")
    public Set<AttributeVariant> getAttributeVariants() {
        return this.attributeVariants;
    }
    
    public void setAttributeVariants(Set<AttributeVariant> attributeVariants) {
        this.attributeVariants = attributeVariants;
    }




}


