package model;
// Generated Nov 15, 2023 12:07:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * ProduvtAttribute generated by hbm2java
 */
@Entity
@Table(name="produvt_attribute"
    ,catalog="j2e_ecom_db"
)
public class ProduvtAttribute  implements java.io.Serializable {


     private Integer id;
     private String attributeName;
     private String attributeType;
     private int productId;
     private Set<Product> products = new HashSet<Product>(0);

    public ProduvtAttribute() {
    }

	
    public ProduvtAttribute(int productId) {
        this.productId = productId;
    }
    public ProduvtAttribute(String attributeName, String attributeType, int productId, Set<Product> products) {
       this.attributeName = attributeName;
       this.attributeType = attributeType;
       this.productId = productId;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="attribute_name", length=50)
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    
    @Column(name="attribute_type", length=50)
    public String getAttributeType() {
        return this.attributeType;
    }
    
    public void setAttributeType(String attributeType) {
        this.attributeType = attributeType;
    }

    
    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="product_has_produvt_attribute", catalog="j2e_ecom_db", joinColumns = { 
        @JoinColumn(name="produvt_attribute_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false) })
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


