package model;
// Generated Dec 18, 2023 10:41:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartItem generated by hbm2java
 */
@Entity
@Table(name="cart_item"
    ,catalog="j2e_ecom_db"
)
public class CartItem  implements java.io.Serializable {


     private Integer id;
     private AttributeVariant attributeVariant;
     private Cart cart;
     private Product product;
     private Integer qty;
     private Double unitprice;
     private Double total;
     private Double discount;
     private Double unitDiscount;

    public CartItem() {
    }

	
    public CartItem(Cart cart, Product product) {
        this.cart = cart;
        this.product = product;
    }
    public CartItem(AttributeVariant attributeVariant, Cart cart, Product product, Integer qty, Double unitprice, Double total, Double discount, Double unitDiscount) {
       this.attributeVariant = attributeVariant;
       this.cart = cart;
       this.product = product;
       this.qty = qty;
       this.unitprice = unitprice;
       this.total = total;
       this.discount = discount;
       this.unitDiscount = unitDiscount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="attribute_variant_id")
    public AttributeVariant getAttributeVariant() {
        return this.attributeVariant;
    }
    
    public void setAttributeVariant(AttributeVariant attributeVariant) {
        this.attributeVariant = attributeVariant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cart_id", nullable=false)
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    
    @Column(name="unitprice", precision=22, scale=0)
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }

    
    @Column(name="total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }

    
    @Column(name="discount", precision=22, scale=0)
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    
    @Column(name="unit_discount", precision=22, scale=0)
    public Double getUnitDiscount() {
        return this.unitDiscount;
    }
    
    public void setUnitDiscount(Double unitDiscount) {
        this.unitDiscount = unitDiscount;
    }




}


