package model;
// Generated Dec 18, 2023 10:41:18 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="j2e_ecom_db"
)
public class Order  implements java.io.Serializable {


     private String orderId;
     private Customer customer;
     private PaymentStatus paymentStatus;
     private Address address;
     private Date orderDate;
     private Date updateDate;
     private Date estimatedDeliveryDate;
     private Double total;
     private Double discount;
     private String trackingNumber;
     private String lastStatus;
     private Date orderDeliveredCustomerDate;
     private Set<OrderHasOrderStatus> orderHasOrderStatuses = new HashSet<OrderHasOrderStatus>(0);
     private Set<OrderItem> orderItems = new HashSet<OrderItem>(0);

    public Order() {
    }

	
    public Order(String orderId, Customer customer, PaymentStatus paymentStatus,Address address) {
        this.orderId = orderId;
        this.customer = customer;
        this.paymentStatus = paymentStatus;
        this.address = address;
    }
    public Order(String orderId, Customer customer, PaymentStatus paymentStatus,Address address, Date orderDate, Date updateDate, Date estimatedDeliveryDate, Double total, Double discount, String trackingNumber,String lastStatus, Date orderDeliveredCustomerDate, Set<OrderHasOrderStatus> orderHasOrderStatuses, Set<OrderItem> orderItems) {
       this.orderId = orderId;
       this.customer = customer;
       this.paymentStatus = paymentStatus;
       this.address = address;
       this.orderDate = orderDate;
       this.updateDate = updateDate;
       this.estimatedDeliveryDate = estimatedDeliveryDate;
       this.total = total;
       this.discount = discount;
       this.trackingNumber = trackingNumber;
       this.lastStatus = lastStatus;
       this.orderDeliveredCustomerDate = orderDeliveredCustomerDate;
       this.orderHasOrderStatuses = orderHasOrderStatuses;
       this.orderItems = orderItems;
    }
   
     @Id 

    
    @Column(name="order_id", unique=true, nullable=false, length=150)
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payment_status_id", nullable=false)
    public PaymentStatus getPaymentStatus() {
        return this.paymentStatus;
    }
    
    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="address_id", nullable=false)
    public Address getAddress() {
        return this.address;
    }
    
    public void setPaymentStatus(Address address) {
        this.address = address;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_date", length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="estimated_delivery_date", length=19)
    public Date getEstimatedDeliveryDate() {
        return this.estimatedDeliveryDate;
    }
    
    public void setEstimatedDeliveryDate(Date estimatedDeliveryDate) {
        this.estimatedDeliveryDate = estimatedDeliveryDate;
    }

    
    @Column(name="total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }

    
    @Column(name="discount", precision=22, scale=0)
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    @Column(name="last_status", length=200)
    public String getLastStatus() {
        return this.lastStatus;
    }
    
    public void setLastStatus(String lastStatus) {
        this.lastStatus = lastStatus;
    }
    
    @Column(name="tracking_number", length=100)
    public String getTrackingNumber() {
        return this.trackingNumber;
    }
    
    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="order_delivered_customer_date", length=19)
    public Date getOrderDeliveredCustomerDate() {
        return this.orderDeliveredCustomerDate;
    }
    
    public void setOrderDeliveredCustomerDate(Date orderDeliveredCustomerDate) {
        this.orderDeliveredCustomerDate = orderDeliveredCustomerDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderHasOrderStatus> getOrderHasOrderStatuses() {
        return this.orderHasOrderStatuses;
    }
    
    public void setOrderHasOrderStatuses(Set<OrderHasOrderStatus> orderHasOrderStatuses) {
        this.orderHasOrderStatuses = orderHasOrderStatuses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="order")
    public Set<OrderItem> getOrderItems() {
        return this.orderItems;
    }
    
    public void setOrderItems(Set<OrderItem> orderItems) {
        this.orderItems = orderItems;
    }




}


